### ISSUE TITLE
save mxnet model not working for channels last format

### ISSUE THREAD

**Issue by roywei** [awslabs/keras-apache-mxnet#109]
Following this tutorial for saving mxnet native models, works fine if `data_format` is `channels_first` in `~/.keras/keras.json`:
https://github.com/awslabs/keras-apache-mxnet/blob/master/docs/mxnet_backend/save_mxnet_model.md

If I change to `channels_last`,
```
data_names, data_shapes = save_mxnet_model(model=model, prefix='mnist_cnn', epoch=0)
print(data_names)
print(data_shapes)
```
gives the following output:
``` 
['/conv2d_1_input1'] 
[DataDesc[/conv2d_1_input1,(128L, 28L, 28L, 1L),float32,NCHW]]
```

In DataDesc, it's still NCHW (channels first) format.
Leading to an error when loading back into mxnet code (note: changed data shape to channels last):

```
import numpy as np
import mxnet as mx

# Step1: Load the model in MXNet

# Use the same prefix and epoch parameters we used in save_mxnet_model API.
sym, arg_params, aux_params = mx.model.load_checkpoint(prefix='mnist_cnn', epoch=0)

# We use the data_names and data_shapes returned by save_mxnet_model API.
mod = mx.mod.Module(symbol=sym, 
                    data_names=['/conv2d_1_input1'], 
                    context=mx.cpu(), 
                    label_names=None)
mod.bind(for_training=False, 
         data_shapes=[('/conv2d_1_input1', (1, 28, 28, 1))], 
         label_shapes=mod._label_shapes)
```

Error Message:
```
 from ._conv import register_converters as _register_converters
infer_shape error. Arguments:
  /conv2d_1_input1: (1, 1L, 28L, 28L)
Traceback (most recent call last):
  File "test_mnist.py", line 27, in <module>
    result = mod.predict(data_iter)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py", line 371, in predict
    self.forward(eval_batch, is_train=False)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 610, in forward
    self.reshape(new_dshape, new_lshape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 471, in reshape
    self._exec_group.reshape(self._data_shapes, self._label_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 382, in reshape
    self.bind_exec(data_shapes, label_shapes, reshape=True)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 358, in bind_exec
    allow_up_sizing=True, **dict(data_shapes_i + label_shapes_i))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/executor.py", line 402, in reshape
    arg_shapes, _, aux_shapes = self._symbol.infer_shape(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 990, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol/symbol.py", line 1120, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator conv2d_1/conv2d2: Shape inconsistent, Provided = [32,1,3,3], inferred shape=(32,28,3,3)
```

**Comment by roywei** [comment]
On GPU, saving mxnet model is not working fine due to weight not synced.
Adding `mxnet_model._sync_weights()`  [here](https://github.com/awslabs/keras-apache-mxnet/blob/master/keras/models.py#L91) didn't fix the problem, need to investigate further.

**Comment by sandeep-krishnamurthy** [comment]
Verified the following:

1. Channels_Last. Keras Model (h5) save and load. CIFAR10_MLP/CNN/ResNet20. Train a Model, save the model with Keras model.save() and load back the keras h5 model. Validation accuracy of the loaded model and the original model is same.

**Comment by roywei** [comment]
Verified for channels_first everything is working, channels_last is not working properly as described in issue.
