### ISSUE TITLE
Optimizers missing with MXNet backend

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [awslabs/keras-apache-mxnet#27]
Following optimizers are not implemented yet for MXNet backend.
1. [x] Adamax
2. [x] NAdam
3. [ ] Adam_AMSGrad

**Comment by sandeep-krishnamurthy** [comment]
Closing in favor of https://github.com/awslabs/keras-apache-mxnet/issues/18

**Comment by edmondja** [comment]
Will it fix this error I have ?


  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/optimizers.py", line 706, in <module>
    SGD, Adagrad, Adadelta, Adam, Adamax, RMSprop, Nadam = K.get_optimizers()

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/backend/mxnet_backend.py", line 5058, in get_optimizers
    class Adamax(MXOptimizer, mx.optimizer.Adamax):

AttributeError: module 'mxnet.optimizer' has no attribute 'Adamax'

**Comment by roywei** [comment]
@edmondja which version of mxnet are you using?
A reproducible code snippet would help use debug.
Thanks!

**Comment by edmondja** [comment]
Thanks to you for helping.


import os
os.environ['KERAS_BACKEND'] = 'mxnet'

import keras
Using MXNet backend
Traceback (most recent call last):

  File "<ipython-input-2-88d96843a926>", line 1, in <module>
    import keras

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/utils/__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/utils/multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/layers/__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/engine/__init__.py", line 7, in <module>
    from .network import get_source_inputs

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/engine/network.py", line 15, in <module>
    from . import saving

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/engine/saving.py", line 15, in <module>
    from .. import optimizers

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/optimizers.py", line 706, in <module>
    SGD, Adagrad, Adadelta, Adam, Adamax, RMSprop, Nadam = K.get_optimizers()

  File "/Users/edmondjacoupeau/anaconda/lib/python3.6/site-packages/keras/backend/mxnet_backend.py", line 5058, in get_optimizers
    class Adamax(MXOptimizer, mx.optimizer.Adamax):

AttributeError: module 'mxnet.optimizer' has no attribute 'Adamax'

keras-mxnet-2.2.0 with pip install --upgrade keras-mxnet on osx sierra, mbp early 2015.

**Comment by sandeep-krishnamurthy** [comment]
Can you please verify `mxnet` version?
You can install MXNet on Mac with  - `pip install mxnet --user`

**Comment by edmondja** [comment]
pip install mxnet --user
Requirement already satisfied: mxnet in ./anaconda/lib/python3.6/site-packages (0.10.0.post2)

**Comment by edmondja** [comment]
Yes sorry it was just the version. I dont know for which reason I had a weird version...
Works fine now.
